### PR TITLE
refactor: update app card subtitle

### PR DESCRIPTION
**Pull request by enesozturk**
# Description

Updated the App Card description to render host name whether it's verified or not

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Draft PR (breaking/non-breaking change which needs more work for having a proper functionality _[Mark this PR as ready to review only when completely ready]_)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by devceline — COMMENTED** [review]
Maybe I've missed the context for this, can you point me to where we talked about this

**Comment by enesozturk** [comment]
> Maybe I've missed the context for this, can you point me to where we talked about this

For sure, tagging you in the Slack conversation now

**Review by devceline — APPROVED** [review]
LGTM

**Comment by enesozturk** [comment]
Slack conversation: https://walletconnect.slack.com/archives/C044SKFKELR/p1701182002816599?thread_ts=1701179393.554649&cid=C044SKFKELR

**Pull request merged**
