### PR TITLE
feat: add support page to settings

### PR DESCRIPTION
**Pull request by enesozturk**
# Description

Add a support page to the settings. 

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# Fixes/Resolves (Optional)

Closes https://github.com/WalletConnect/web3inbox-planning/issues/39
Closes https://github.com/WalletConnect/web3inbox-planning/issues/50

# Examples/Screenshots (Optional)

Screenshot 2024-01-12 at 11 28 21

Screenshot 2024-01-12 at 11 28 32

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by chadyj** [comment]
Thanks @enesozturk. A few small things:

1. Typo
> Get support our Discord
Should be
> Get support at our Discord

2. Can you please direct link to FAQ with a named anchor?
eg https://web3inbox.com/#faq

3. Weird issue when support icon is active. Turns into a blob
Screenshot 2024-01-12 at 11 10 48

**Comment by enesozturk** [comment]
@chadyj Made updates. 

An addition; Moved the appearance settings to the second place, since it doesn't have any functionality yet. We could even remove it since we show a feature that doesn't work. Wdyt?

**Comment by chadyj** [comment]
Thanks ship it.

Created a reminder issue for the anchor https://github.com/WalletConnect/www-web3inbox/issues/11

**Comment by chadyj** [comment]
> We could even remove it since we show a feature that doesn't work. Wdyt?

Lets keep it otherwise it looks a little lonely

**Review by svenvoskamp — APPROVED** [review]

**Pull request merged**
